/**
 * The creative engine — Miles generating ad creative on demand (the "makes the
 * ads" half of a marketing employee). Copy is generated here from the vertical
 * packs (offers + urgency), deterministically and testably; the photo/video is
 * generated by fal.ai when a key is set (see fal.ts), and falls back to a
 * templated preview card otherwise. Same "mock by default, live when configured"
 * pattern as the connector and the LLM.
 */
import { getPack } from '../packs/index.js';
import { suggestOffers } from '../packs/apply.js';

export interface CreativeRequest {
  vertical?: string;
  category?: string;
  /** An offer line to feature; if omitted we pick from the pack's offer library. */
  offer?: string;
  businessName?: string;
  city?: string;
  /** The customer's services (first-party), woven into the copy when present. */
  services?: string;
}

export interface AdCreative {
  /** The creative angle — offer, urgency, or trust. */
  angle: string;
  headline: string;
  body: string;
  cta: string;
  /** The prompt handed to the image model (fal.ai) for the visual. */
  imagePrompt: string;
  /** Filled in when a real image was generated; otherwise the UI shows a preview. */
  imageUrl?: string;
}

// A photoreal subject per home-services category, so the generated visual matches the trade.
const IMAGE_SUBJECT: Record<string, string> = {
  plumbing: 'a friendly professional plumber fixing a sink in a bright modern kitchen',
  hvac: 'an HVAC technician servicing an outdoor air-conditioning unit beside a suburban house on a sunny day',
  electrical: 'a licensed electrician working safely on a residential electrical panel',
  roofing: 'a roofing crew inspecting shingles on a suburban house roof under a clear blue sky',
  garage_door: 'a technician installing a modern garage door on a suburban home',
  water_damage: 'a restoration technician drying a home interior after water damage, professional equipment',
  pest_control: 'a pest-control technician treating the exterior of a suburban home',
  landscaping: 'a landscaper mowing and edging a lush green suburban lawn on a sunny day',
  painting: 'a professional painter rolling fresh paint onto an interior wall of a bright home',
  remodeling: 'a contractor in a newly remodeled modern kitchen, clean and bright',
};
const DEFAULT_SUBJECT = 'a friendly professional home-services technician at a customer’s home, clean uniform';

function firstName(city?: string): string {
  return city ? city.split(',')[0]!.trim() : 'your area';
}

/**
 * Generate three ad variations — one per angle (offer, urgency, trust). Pure and
 * deterministic given the same inputs, so the copy is fully testable.
 */
export function generateAdCopy(req: CreativeRequest): AdCreative[] {
  const pack = getPack(req.vertical);
  const cat = pack.categories.find((c) => c.id === req.category) ?? pack.categories[0]!;
  const biz = req.businessName?.trim() || 'Your Company';
  const place = firstName(req.city);
  const offer =
    req.offer?.trim() || suggestOffers(pack, cat.id, 1)[0]?.headline || 'Fast, reliable service';
  const subject = IMAGE_SUBJECT[cat.id] ?? DEFAULT_SUBJECT;
  const urgent = cat.urgency >= 0.7;
  const imageBase = `professional advertising photography, ${subject}, high quality, natural light, sharp focus`;

  return [
    {
      angle: 'Offer',
      headline: offer,
      body: `${biz} — trusted ${cat.label.toLowerCase()} in ${place}.${req.services ? ` We handle ${req.services}.` : ''} Book online in under a minute and lock in this offer today.`,
      cta: 'Book now',
      imagePrompt: imageBase,
    },
    {
      angle: urgent ? 'Urgency' : 'Value',
      headline: urgent
        ? `${cat.label} problem? We can be there today.`
        : `Upgrade your ${cat.label.toLowerCase()} the right way`,
      body: urgent
        ? `${biz} — same-day ${cat.label.toLowerCase()} in ${place}. Fast response, upfront pricing, no surprises. ${offer}.`
        : `Quality ${cat.label.toLowerCase()} from ${biz}, done right the first time. Free quotes for ${place}. ${offer}.`,
      cta: urgent ? 'Call now' : 'Get a free quote',
      imagePrompt: `${imageBase}, ${urgent ? 'urgent friendly and reassuring tone' : 'premium quality craftsmanship'}`,
    },
    {
      angle: 'Trust',
      headline: `${place}’s go-to for ${cat.label.toLowerCase()}`,
      body: `Licensed, insured, and rated 5 stars by your neighbors. ${biz} makes ${cat.label.toLowerCase()} easy — ${offer}.`,
      cta: 'Get your free quote',
      imagePrompt: `${imageBase}, warm trustworthy local business feel, smiling technician`,
    },
  ];
}
